apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-deployment
  labels:
    app: tasklist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklist
  template:
    metadata:
      labels:
        app: tasklist
    spec:
      containers:
        - name: tasklist
          image: mpho15/spring-boot-tasklist:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"

            - name: DB_HOST
              value: "host.docker.internal" 
              
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://10.255.255.254:5432/taskdb"
  
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
  
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
