apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-tasklist
  labels:
    app: spring-boot-tasklist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-tasklist
  template:
    metadata:
      labels:
        app: spring-boot-tasklist
    spec:
      containers:
        - name: spring-boot-tasklist
          image: mpho15/spring-boot-tasklist:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
