apiVersion: v1
kind: Service
metadata:
  name: tasklist-service
spec:
  type: LoadBalancer
  selector:
    app: tasklist
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 32000
