apiVersion: v1
kind: Service
metadata:
  name: spring-boot-tasklist-service
  labels:
    app: spring-boot-tasklist
spec:
  selector:
    app: spring-boot-tasklist
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
